spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  application:
    name: codesentry
  ai:
    model:
      chat: google-genai
    google:
      genai:
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001
            dimensions: 768
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.5-flash-lite
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true
    mcp:
      server:
        name: codesentry-mcp
        version: 1.0.0
        protocol: STREAMABLE
logging:
  level:
    org.springframework.ai: DEBUG
