spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
  application:
    name: codesentry
  ai:
    model:
      chat: google-genai
    google:
      genai:
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001
            dimensions: 768
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.5-flash-lite
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true
logging:
  level:
    org.springframework.ai: DEBUG
